<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>ASM</string>
	</array>
	<key>name</key>
	<string>Assembly x86 Intel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.8086/8088</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function 8086/8088 case insensitive</string>
			<key>match</key>
			<string>\b(?i:aaa|aad|aam|aas|adc|add|and|call|cbw|clc|cld|cli|cmc|cmp|cmpsb|cmpsw|cwd|daa|das|dec|div|esc|hlt|idiv|imul|in|inc|int|into|iret|ja|jae|jb|jbe|jc|jcxz|je|jg|jge|jl|jle|jna|jnae|jnb|jnbe|jnc|jne|jng|jnge|jnl|jnle|jno|jnp|jns|jnz|jo|jp|jpe|jpo|js|jz|jmp|lahf|lar|lds|lea|les|lock|lodsb|lodsw|loop|loope|loopz|loopnz|loopne|mov|movsb|movsw|mul|neg|nop|not|or|out|pop|popf|push|pushf|rcl|rcr|rep|repe|repne|repnz|repz|ret|retn|retf|rol|ror|sahf|sal|sar|sbb|scasb|scasw|shl|shr|stc|std|sti|stosb|stosw|sub|test|wait|xchg|xlat||xor)\b</string>
			<key>name</key>
			<string>support.class.8086/8088</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.80186/80188</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function 80186/80188 case insensitive</string>
			<key>match</key>
			<string>\b(?i:bound|enter|ins|leave|outs|popa|pusha)\b</string>
			<key>name</key>
			<string>support.class.80186/80188</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.80286</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function 80286 case insensitive</string>
			<key>match</key>
			<string>\b(?i:arpl|clts|lar|lgdt|lidt|lldt|lmsw|loadall|lsl|ltr|sgdt|sidt|sldt|smsw|str|verr|verw)\b</string>
			<key>name</key>
			<string>support.class.80286</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.80386</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function 80386 case insensitive</string>
			<key>match</key>
			<string>\b(?i:bsf|bsr|bt|btc|btr|bts|cdq|cmpsd|cwde|insb|insw|insd|iret|iretd|jcxz|jecxz|lsf|lgs|lss|lodsd|loopw|loopd|loopew|looped|loopzw|loopzd|loopnew|loopned|loopnzw|loopnzd|movsw|movsd|movsx|movzx|popad|popfd|pushad|pushfd|scasd|seta|setae|setb|setbe|setc|sete|setg|setge|setl|setle|setna|setnae|setnb|setnbe|setnc|setne|setng|setnge|setnl|setnle|setno|setnp|setns|setnz|seto|setp|setpe|setpo|sets|setz|shld|shrd|stosb|stosw)\b</string>
			<key>name</key>
			<string>support.class.80386</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.80484</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function 80486 case insensitive</string>
			<key>match</key>
			<string>\b(?i:bswap|cmpxchg|invd|invlpg|wbinvd|xadd)\b</string>
			<key>name</key>
			<string>support.class.80486</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.pentium</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Pentium case insensitive</string>
			<key>match</key>
			<string>\b(?i:cpuid|cmpxchg8b|rdmsr|rdtsc|wrmsr|rsm)\b</string>
			<key>name</key>
			<string>support.class.pentium</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.mmx</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Pentium MMX case insensitive</string>
			<key>match</key>
			<string>\b(?i:rdpmc|emms|movd|movq|packssdw|packsswb|packuswb|paddb|paddd|paddsb|paddsw|paddusb|paddusw|paddw|pand|pandn|pcmpeqb|pcmpeqd|pcmpeqw|pcmpgtb|pcmpgtd|pcmpgtw|pmaddwd|pmulhw|pmullw|por|pslld|psllq|psllw|psrad|psraw|psrld|psrlq|psrlw|psubb|psubd|psubsb|psubsw|psubusb|psubusw|psubw|punpckhbw|punpckhdq|punpckhwd|punpcklbw|punpckldq|punpcklwd|pxor|paveb|paddsiw|pmagw|pdistib|psubsiw|pmvzb|pmulhrw|pmvnzb|pmvlzb|pmvgezb|pmulhriw|pmachriw)\b</string>
			<key>name</key>
			<string>support.class.mmx</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.3dnow!</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Pentium case insensitive</string>
			<key>match</key>
			<string>\b(?i:syscall|sysret|femms|pavgusb|pf2id|pfacc|pfadd|pfcmpeq|pfcmpge|pfcmpgt|pfmax|pfmin|pfmul|pfrcp|pfrcpit1|pfrcpit2|pfrsqit1|pfrsqrt|pfsub|pfsubr|pi2fd|pmulhrw|prefetch|prefetchw|pf2iw|pfnacc|pfpnacc|pi2fw|pswapd)\b</string>
			<key>name</key>
			<string>support.class.3dnow!</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.pentiumpro</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Pentium Pro case insensitive</string>
			<key>match</key>
			<string>\b(?i:cmova|cmovae|cmovb|cmovbe|cmovc|cmove|cmovg|cmovge|cmovl|cmovle|cmovna|cmovnae|cmovnb|cmovnbe|cmovnc|cmovne|cmovng|cmovnge|cmovnl|cmovnle|cmovno|cmovnp|cmovns|cmovnz|cmovo|cmovp|cmovpe|cmovpo|cmovs|cmovz|sysenter|sysexit|ud2|fcmov|fcmovb|fcmovbe|fcmove|fcmovnb|fcmovnbe|fcmovne|fcmovnu|fcmovu|fcomi|fcomip|fucomi|fucomip)\b</string>
			<key>name</key>
			<string>support.class.pentiumpro</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.sse</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function SSE case insensitive</string>
			<key>match</key>
			<string>\b(?i:maskmovq|movntps|movntq|prefetch0|prefetch1|prefetch2|prefetchnta|sfence|fxrstor|fxsave)\b</string>
			<key>name</key>
			<string>support.class.sse</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.sse2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function SSE2 case insensitive</string>
			<key>match</key>
			<string>\b(?i:clflush|lfence|maskmovdqu|mfence|movntdq|movnti|movntpd|pause)\b</string>
			<key>name</key>
			<string>support.class.sse2</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>constant names case insensitive</string>
			<key>match</key>
			<string>(?i:equ|org|label|byte|word|dword|qword|tbyte|near|far|struct|ends|offset|short|length|size|seg|public|extern|db|dw|dd|dq|dt|goto|\.code|\.data|\.stack|\.model|\.end)</string>
			<key>name</key>
			<string>support.class</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.reg</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Names registers case insensitive</string>
			<key>match</key>
			<string>\b(?i:al|ah|ax|eax|bl|bh|bx|ebx|cl|ch|cx|ecx|dl|dh|dx|edx|si|esi|di|edi|bp|ebp|sp|esp|cs|ds|ss|es|fs|gs|ip|eip|eflags|id|vip|vif|ac|vm|rf|nt|iopl|of|df|if|tf|sf|zf|af|pf|cf|st0|st1|st2|st3|st4|st5|st6|st7|mm0|mm1|mm2|mm3|mm4|mm5|mm6|mm7|xmm0|xmm1|xmm2|xmm3|xmm4|xmm5|xmm6|xmm7|xmcrt|cr0|cr2|cr3|cr4|gdtr|ldtr|idtr|dr0|dr1|dr2|dr3|dr6|dr7|msr|rax|rbx|rcx|rdx|rsi|rdi|rsp|rbp|r8|r9|r10|r11|r12|r13|r14|r15|r8d|r9d|r10d|r11d|r12d|r13d|r14d|r15d|r8w|r9w|r10w|r11w|r12w|r13w|r14w|r15w|r8l|r9l|r10l|r11l|r12l|r13l|r14l|r15l)\b</string>
			<key>name</key>
			<string>entity.name.function.reg</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comment line ';'</string>
			<key>match</key>
			<string>\s?(;.*)$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.dec</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Decimal numbers</string>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Exadecimal numbers format: 0xFF</string>
			<key>match</key>
			<string>\b(0x[0-9a-fA-F]+)\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Exadecimal numbers format: FFh</string>
			<key>match</key>
			<string>\b([0-9a-fA-F]+h)\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.bin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Binary numbers format: 100101b</string>
			<key>match</key>
			<string>\b([0-1]+b)\b</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String caracter</string>
			<key>match</key>
			<string>(?&lt;!\$)(['"])(.*)\1(?!\$)</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.label</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assembly label</string>
			<key>match</key>
			<string>(\w+[:])</string>
			<key>name</key>
			<string>keyword.control.label</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm</string>
	<key>uuid</key>
	<string>94483e06-77e4-431e-be96-a456fe05c523</string>
</dict>
</plist>
